<?php

declare(strict_types=1);

/*
 * Site chrome text for the generated documentation site (both languages).
 * Guide content lives in tools/docs/content/<lang>/<slug>.html; everything
 * else a reader sees (navigation, labels, home page copy) is defined here.
 *
 * Placeholders: %s / %d are filled with sprintf by the generator.
 */

return [
    'site' => [
        'name' => 'RTLY-Kit',
        'package' => 'enaxon/rtly-kit',
        'install' => 'composer require enaxon/rtly-kit',
        'repo' => 'https://github.com/ehsanenaloo/RTLY-Kit',
        'issues' => 'https://github.com/ehsanenaloo/RTLY-Kit/issues',
        'license' => 'MIT',
        'php' => '8.2',
    ],

    'langs' => [
        'fa' => ['name' => 'فارسی', 'dir' => 'rtl', 'locale' => 'fa_IR'],
        'en' => ['name' => 'English', 'dir' => 'ltr', 'locale' => 'en_US'],
    ],

    'fa' => [
        'tagline' => 'جعبه‌ابزار فارسی و عربی برای PHP',
        'doc_title' => 'راهنمای کاربر',
        'nav' => [
            'primary' => 'ناوبری اصلی',
            'overview' => 'نمای کلی',
            'quick_start' => 'شروع سریع',
            'all' => 'همهٔ راهنماها',
            'github' => 'گیت‌هاب',
        ],
        'skip' => 'پرش به محتوا',
        'search_label' => 'جست‌وجو در راهنما',
        'search_placeholder' => 'جست‌وجو در راهنما',
        'lang_switch' => 'English',
        'lang_switch_label' => 'Switch to English',
        'page' => [
            'home' => 'خانه',
            'guides' => 'راهنماها',
            'breadcrumb' => 'مسیر صفحه',
            'on_this_page' => 'در این صفحه',
            'menu' => 'فهرست راهنماها',
            'menu_label' => 'راهنماها',
            'previous' => 'قبلی',
            'next' => 'بعدی',
            'reading_nav' => 'صفحهٔ قبلی و بعدی',
            'anchor' => 'پیوند به این بخش',
            'table' => 'جدول',
            'group' => 'گروه',
        ],
        'all' => [
            'title' => 'همهٔ راهنماها',
            'description' => 'فهرست کامل راهنماهای RTLY-Kit بر اساس موضوع. با کادر زیر می‌توانید فهرست را فیلتر کنید.',
            'filter_label' => 'فیلتر راهنماها',
            'filter_placeholder' => 'مثلاً جلالی یا کد ملی',
            'status' => '%d از %d راهنما نمایش داده می‌شود',
            'empty' => 'راهنمایی با این عبارت پیدا نشد.',
        ],
        'groups' => [
            'start' => ['label' => 'شروع کار', 'blurb' => 'نصب و اولین اجرا.'],
            'calendars' => ['label' => 'تقویم‌ها', 'blurb' => 'جلالی، هجری و عبری؛ ساخت، قالب‌بندی، مقایسه و تبدیل.'],
            'validation' => ['label' => 'اعتبارسنجی', 'blurb' => 'کد ملی، شبا، کارت بانکی، موبایل، کد پستی و پلاک با نتیجهٔ ساخت‌یافته.'],
            'numbers-text' => ['label' => 'اعداد و متن', 'blurb' => 'ارقام، جداکنندهٔ هزارگان، عدد به حروف، نرمال‌سازی و تشخیص متن.'],
            'dates-and-times' => ['label' => 'تعطیلات و اوقات شرعی', 'blurb' => 'تعطیلات رسمی ایران و محاسبهٔ اوقات شرعی.'],
            'laravel' => ['label' => 'لاراول', 'blurb' => 'سرویس‌پرووایدر، قواعد اعتبارسنجی، فاساد و کست الکوئنت.'],
            'reference' => ['label' => 'مرجع', 'blurb' => 'توابع کمکی، خطاها، پایداری API، دقت داده‌ها، محدودیت‌ها و ارتقا.'],
        ],
        'home' => [
            'meta_title' => 'RTLY-Kit، جعبه‌ابزار فارسی و عربی برای PHP',
            'eyebrow' => 'enaxon/rtly-kit',
            'title' => 'RTLY-Kit',
            'subtitle' => 'جعبه‌ابزار فارسی و عربی برای PHP',
            'lead' => 'تقویم جلالی، هجری و عبری، اعتبارسنجی‌های ایرانی، اعداد و متن فارسی و عربی، تعطیلات و اوقات شرعی در یک کتابخانهٔ typed و immutable. یکپارچگی با Carbon و لاراول اختیاری است.',
            'cta_start' => 'شروع سریع',
            'cta_all' => 'همهٔ راهنماها',
            'cta_github' => 'مخزن در گیت‌هاب',
            'hero_note' => 'PHP نسخهٔ %s یا بالاتر؛ فقط افزونهٔ mbstring لازم است. مجوز %s.',
            'install_title' => 'نصب',
            'install_lead' => 'با Composer نصب کنید و بلافاصله استفاده کنید؛ فایل تنظیمات یا مرحلهٔ انتشار وجود ندارد.',
            'sample_title' => 'نمونهٔ سی‌ثانیه‌ای',
            'can_title' => 'چه کارهایی می‌توانید بکنید',
            'can_lead' => 'هر مورد به راهنمای مربوط به خودش پیوند دارد.',
            'can_items' => [
                ['تاریخ جلالی، هجری و عبری را بسازید، قالب‌بندی کنید، جمع و تفریق کنید، مقایسه کنید و به هم تبدیل کنید.', 'jalali'],
                ['کد ملی، شبا، کارت بانکی، شمارهٔ موبایل، کد پستی و پلاک خودرو را اعتبارسنجی کنید و کد خطای ماشین‌خوان بگیرید.', 'validators-overview'],
                ['ارقام فارسی، عربی و انگلیسی را به هم تبدیل کنید و اعداد را با جداکنندهٔ هزارگان قالب‌بندی کنید.', 'digits-and-format'],
                ['عدد را به حروف فارسی یا عربی بنویسید و از ترتیبی‌ها استفاده کنید.', 'number-words'],
                ['متن را نرمال کنید (ک و ی عربی، نیم‌فاصله)، جهت و خط را تشخیص دهید و نامک (slug) فارسی بسازید.', 'text-tools'],
                ['تعطیلات رسمی ایران را بپرسید و روز کاری بعدی را پیدا کنید.', 'holidays'],
                ['اوقات شرعی را برای یک شهر و روش محاسبه به‌دست آورید.', 'prayer-times'],
                ['ماکروهای Carbon، قواعد اعتبارسنجی، فاساد و کست الکوئنت لاراول را بدون تنظیم اضافی به کار ببرید.', 'laravel-setup'],
            ],
            'stats_title' => 'در یک نگاه',
            'stats' => [
                'calendars' => 'تقویم',
                'validators' => 'اعتبارسنج',
                'helpers' => 'تابع کمکی',
                'prayer_methods' => 'روش اوقات شرعی',
                'locales' => 'زبان پیام‌های اعتبارسنجی',
                'guides' => 'راهنما',
            ],
            'stats_note' => 'این اعداد هنگام ساخت سایت از خودِ کد شمرده می‌شوند.',
            'honest_title' => 'محدودیت‌ها را صادقانه بخوانید',
            'honest_text' => 'جدول ام‌القری، تعطیلات مذهبی ایران (که با رؤیت هلال تعیین می‌شود) و اوقات شرعی دقت مشخصی دارند و بعضی جدول‌ها فقط با دو منبع تأیید شده‌اند. پیش از استفاده در محیط واقعی، صفحهٔ دقت و منبع داده‌ها را ببینید.',
            'honest_cta' => 'دقت و منبع داده‌ها',
            'groups_title' => 'راهنماها بر اساس موضوع',
            'groups_lead' => 'از هر موضوع شروع کنید؛ ترتیب فهرست از ساده به مرجع است.',
            'open' => 'باز کردن',
        ],
        'footer' => [
            'text' => 'راهنمای RTLY-Kit · مجوز %s',
            'repo' => 'مخزن در گیت‌هاب',
            'issues' => 'گزارش مشکل',
        ],
        'llms' => [
            'intro' => 'کتابخانهٔ PHP (نسخهٔ 8.2 به بالا، بدون بستهٔ اجباری Composer) برای کار با متن راست‌به‌چپ فارسی و عربی: تقویم جلالی، هجری و عبری، اعتبارسنجی‌های ایرانی، اعداد و متن، تعطیلات و اوقات شرعی، با یکپارچگی اختیاری Carbon و لاراول.',
            'meta' => 'بسته: %s (نصب: %s). نیازمند PHP %s یا بالاتر. منبع: %s',
            'notes_title' => 'نکته‌ها برای خوانندگان و ابزارها',
            'notes' => [
                'توابع کمکی در فضای نام RtlyKit هستند: `use function RtlyKit\jdate;`. نام‌های سراسری کوتاه فقط با `\RtlyKit\Globals::register();` فعال می‌شوند.',
                'همهٔ استثناها از `RtlyKit\Exceptions\RtlyKitException` ارث می‌برند؛ اعتبارسنج‌ها هرگز استثنا پرتاب نمی‌کنند و `Result` برمی‌گردانند.',
                'نقطه‌های ورود تقویم فقط سال‌های بازهٔ پشتیبانی‌شده را می‌پذیرند و در غیر این صورت `InvalidDateException` پرتاب می‌کنند.',
            ],
            'accuracy_note' => 'محدودیت‌های دقت جدول ام‌القری، تعطیلات مذهبی ایران، اوقات شرعی و جدول‌های داده در %s آمده است.',
        ],
        'js' => [
            'dark' => 'حالت تیره',
            'light' => 'حالت روشن',
            'to_dark' => 'تغییر به پوستهٔ تیره',
            'to_light' => 'تغییر به پوستهٔ روشن',
            'copy' => 'کپی',
            'copied' => 'کپی شد',
            'copy_failed' => 'انتخاب شد؛ کپی کنید',
            'copy_label' => 'کپی کردن کد بالا',
            'no_results' => 'نتیجه‌ای پیدا نشد. عبارت کوتاه‌تری امتحان کنید.',
            'loading' => 'فهرست جست‌وجو هنوز بارگذاری می‌شود. چند لحظه بعد دوباره امتحان کنید.',
            'results' => 'نتایج جست‌وجو',
            'status' => '%d از %d راهنما نمایش داده می‌شود',
            'suggest' => 'نسخهٔ فارسی',
        ],
    ],

    'en' => [
        'tagline' => 'The Persian and Arabic RTL toolkit for PHP',
        'doc_title' => 'User guide',
        'nav' => [
            'primary' => 'Primary',
            'overview' => 'Overview',
            'quick_start' => 'Quick start',
            'all' => 'All guides',
            'github' => 'GitHub',
        ],
        'skip' => 'Skip to content',
        'search_label' => 'Search the guide',
        'search_placeholder' => 'Search the guide',
        'lang_switch' => 'فارسی',
        'lang_switch_label' => 'تغییر به فارسی',
        'page' => [
            'home' => 'Home',
            'guides' => 'Guides',
            'breadcrumb' => 'Breadcrumb',
            'on_this_page' => 'On this page',
            'menu' => 'Browse the guides',
            'menu_label' => 'Guides',
            'previous' => 'Previous',
            'next' => 'Next',
            'reading_nav' => 'Previous and next page',
            'anchor' => 'Link to this section',
            'table' => 'Table',
            'group' => 'Group',
        ],
        'all' => [
            'title' => 'All guides',
            'description' => 'The complete list of RTLY-Kit guides by topic. Use the box below to filter the list.',
            'filter_label' => 'Filter guides',
            'filter_placeholder' => 'For example jalali or national code',
            'status' => '%d of %d guides shown',
            'empty' => 'No guide matches that text.',
        ],
        'groups' => [
            'start' => ['label' => 'Getting started', 'blurb' => 'Install and run your first example.'],
            'calendars' => ['label' => 'Calendars', 'blurb' => 'Jalali, Hijri and Hebrew: create, format, compare and convert.'],
            'validation' => ['label' => 'Validation', 'blurb' => 'National code, Sheba, bank card, mobile, postal code and plate, with structured results.'],
            'numbers-text' => ['label' => 'Numbers and text', 'blurb' => 'Digits, thousands separators, number to words, normalization and detection.'],
            'dates-and-times' => ['label' => 'Holidays and prayer times', 'blurb' => 'Iranian public holidays and prayer time calculation.'],
            'laravel' => ['label' => 'Laravel', 'blurb' => 'Service provider, validation rules, facade and Eloquent cast.'],
            'reference' => ['label' => 'Reference', 'blurb' => 'Helpers, errors, API stability, data accuracy, limits and upgrading.'],
        ],
        'home' => [
            'meta_title' => 'RTLY-Kit, the Persian and Arabic RTL toolkit for PHP',
            'eyebrow' => 'enaxon/rtly-kit',
            'title' => 'RTLY-Kit',
            'subtitle' => 'The Persian and Arabic RTL toolkit for PHP',
            'lead' => 'Jalali, Hijri and Hebrew calendars, Iranian validators, Persian and Arabic numbers and text, holidays and prayer times in one typed, immutable PHP library. Carbon and Laravel integrations are optional.',
            'cta_start' => 'Quick start',
            'cta_all' => 'All guides',
            'cta_github' => 'Repository on GitHub',
            'hero_note' => 'Requires PHP %s or newer; only the mbstring extension is needed. %s licensed.',
            'install_title' => 'Install',
            'install_lead' => 'Install with Composer and use it right away. There is no config file and no publish step.',
            'sample_title' => 'The 30-second example',
            'can_title' => 'What you can do',
            'can_lead' => 'Each item links to its guide.',
            'can_items' => [
                ['Create, format, add to, compare and convert Jalali, Hijri and Hebrew dates.', 'jalali'],
                ['Validate national codes, Sheba numbers, bank cards, mobile numbers, postal codes and vehicle plates and get machine-readable error codes.', 'validators-overview'],
                ['Convert between Persian, Arabic and English digits and format numbers with thousands separators.', 'digits-and-format'],
                ['Write numbers as Persian or Arabic words and use ordinals.', 'number-words'],
                ['Normalize text (Arabic ka and ya, ZWNJ), detect direction and script, and build Persian slugs.', 'text-tools'],
                ['Ask whether a day is an Iranian public holiday and find the next business day.', 'holidays'],
                ['Compute prayer times for a city and a calculation method.', 'prayer-times'],
                ['Use the Carbon macros and the Laravel validation rules, facade and Eloquent cast with no extra setup.', 'laravel-setup'],
            ],
            'stats_title' => 'At a glance',
            'stats' => [
                'calendars' => 'calendars',
                'validators' => 'validators',
                'helpers' => 'helper functions',
                'prayer_methods' => 'prayer-time methods',
                'locales' => 'validation message languages',
                'guides' => 'guides',
            ],
            'stats_note' => 'These numbers are counted from the code when the site is built.',
            'honest_title' => 'Read the limits first',
            'honest_text' => 'The Umm al-Qura table, Iranian religious holidays (set by moon sighting) and prayer times have stated accuracy limits, and some data tables are confirmed by only two sources. Before relying on them in production, read the accuracy and data page.',
            'honest_cta' => 'Accuracy and data',
            'groups_title' => 'Guides by topic',
            'groups_lead' => 'Start from any topic. Each list runs from the simple to the reference.',
            'open' => 'Open',
        ],
        'footer' => [
            'text' => 'RTLY-Kit user guide · %s licensed',
            'repo' => 'Repository on GitHub',
            'issues' => 'Report an issue',
        ],
        'llms' => [
            'intro' => 'A PHP library (PHP 8.2 or newer, no required Composer packages) for Persian and Arabic right-to-left work: Jalali, Hijri and Hebrew calendars, Iranian validators, numbers and text, holidays and prayer times, with optional Carbon and Laravel integrations.',
            'meta' => 'Package: %s (install: %s). Requires PHP %s or newer. Source: %s',
            'notes_title' => 'Notes for readers and tools',
            'notes' => [
                'Helpers are namespaced functions: `use function RtlyKit\jdate;`. Short global names are opt-in with `\RtlyKit\Globals::register();`.',
                'Every exception extends `RtlyKit\Exceptions\RtlyKitException`; validators never throw and return a `Result` instead.',
                'Calendar entry points accept only years inside the supported ranges and throw `InvalidDateException` otherwise.',
            ],
            'accuracy_note' => 'Accuracy limits of the Umm al-Qura table, Iranian religious holidays, prayer times and data tables are listed in %s.',
        ],
        'js' => [
            'dark' => 'Dark mode',
            'light' => 'Light mode',
            'to_dark' => 'Switch to dark theme',
            'to_light' => 'Switch to light theme',
            'copy' => 'Copy',
            'copied' => 'Copied',
            'copy_failed' => 'Selected. Press copy.',
            'copy_label' => 'Copy the code example above',
            'no_results' => 'No guide matches. Try a shorter word.',
            'loading' => 'The search index is still loading. Try again in a moment.',
            'results' => 'Search results',
            'status' => '%d of %d guides shown',
            'suggest' => 'English version',
        ],
    ],

    'root' => [
        'title' => 'RTLY-Kit documentation',
        'description' => 'Documentation for RTLY-Kit (enaxon/rtly-kit): choose a language. مستندات RTLY-Kit: یک زبان را انتخاب کنید.',
        'heading' => 'Choose a language',
        'heading_fa' => 'یک زبان را انتخاب کنید',
        'cards' => [
            'fa' => ['title' => 'فارسی', 'text' => 'راهنمای کامل به زبان فارسی (راست‌به‌چپ).'],
            'en' => ['title' => 'English', 'text' => 'The full guide in English.'],
        ],
        'suggest' => ['fa' => 'پیشنهاد برای شما', 'en' => 'Suggested for you'],
        'repo' => 'GitHub',
    ],
];
